"use client";

import React, { useEffect } from "react";
import { useRouter } from "next/navigation";
import { useDashboard } from "@/components/dashboard/DashboardContext";
import { Section, Badge, classNames } from "@/components/dashboard/ui";
import { ArrowLeft, ArrowRight, Play, ServerCog, CheckCircle } from "lucide-react";
import { workflowSteps } from "@/lib/workflow/agent";

export default function ActionExecutionPage() {
  const router = useRouter();
  const { result, status, activeStep, triggerNextStep } = useDashboard();

  useEffect(() => {
    if (!result && status !== "running") {
      router.push("/dashboard/provider-matching");
    }
  }, [result, status, router]);

  async function handleNextStep() {
    await triggerNextStep("action-execution-completed", { actions: result?.actions });
    router.push("/dashboard/final-status");
  }

  const activeIndex = activeStep ? workflowSteps.findIndex(s => s.id === activeStep) : -1;

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="border-b border-slate-200 pb-4 mb-6">
        <h1 className="text-3xl font-bold text-slate-950">Action Execution</h1>
        <p className="text-slate-600 mt-2">
          Review the simulated actions generated by the workflow, including preparation for calls and paperwork.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Timeline Log */}
        <Section eyebrow="Orchestration" title="Workflow Timeline">
          <div className="space-y-5 mt-4">
            {workflowSteps.map((step, index) => {
              const completed = status === "complete" || (status === "running" && index < activeIndex);
              const active = status === "running" && activeStep === step.id;

              return (
                <div className="flex gap-4" key={step.id}>
                  <div className="flex flex-col items-center">
                    <div
                      className={classNames(
                        "flex h-8 w-8 items-center justify-center rounded-full border text-sm font-bold shadow-sm transition-colors",
                        completed ? "border-emerald-300 bg-emerald-100 text-emerald-800" :
                        active ? "border-sky-300 bg-sky-100 text-sky-800 animate-pulse" :
                        "border-slate-200 bg-slate-50 text-slate-400"
                      )}
                    >
                      {completed ? <CheckCircle className="w-5 h-5" /> : index + 1}
                    </div>
                    {index < workflowSteps.length - 1 && (
                      <div className={classNames(
                        "w-px h-8 my-2",
                        completed ? "bg-emerald-200" : "bg-slate-200"
                      )}></div>
                    )}
                  </div>
                  <div className="pb-4 flex-1">
                    <div className="flex flex-wrap items-center gap-3">
                      <h3 className={classNames(
                        "font-semibold text-base",
                        completed || active ? "text-slate-950" : "text-slate-500"
                      )}>{step.label}</h3>
                      {active && <Badge tone="blue">Running</Badge>}
                      {completed && <Badge tone="good">Done</Badge>}
                    </div>
                    <p className="mt-1 text-sm text-slate-600 leading-relaxed">{step.description}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </Section>

        {/* Action Log */}
        <Section eyebrow="Simulation" title="Action Log">
          {!result ? (
            <div className="flex flex-col items-center justify-center p-8 bg-slate-50 border border-slate-200 border-dashed rounded-lg text-slate-500">
              <ServerCog className="w-8 h-8 mb-3 animate-spin duration-3000" />
              <p>Awaiting simulation results...</p>
            </div>
          ) : (
            <div className="space-y-4">
              {result.actions.map((action) => (
                <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md transition-shadow" key={action.id}>
                  <div className="flex flex-wrap items-center justify-between gap-3 mb-2">
                    <span className="font-semibold text-slate-900">{action.label}</span>
                    <Badge tone={action.status === "blocked" ? "danger" : "good"}>
                      {action.status.toUpperCase()}
                    </Badge>
                  </div>
                  <p className="text-sm text-slate-600 leading-relaxed">{action.summary}</p>
                </div>
              ))}
            </div>
          )}
        </Section>
      </div>

      <div className="pt-6 border-t border-slate-200 flex justify-between items-center">
        <button
          onClick={() => router.push("/dashboard/provider-matching")}
          className="group inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Back to Providers
        </button>

        <button
          onClick={handleNextStep}
          disabled={status !== "complete"}
          className="group inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-teal-600 px-6 py-3 font-semibold text-white shadow-sm transition hover:bg-teal-500 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          View Final Status
          <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
        </button>
      </div>
    </div>
  );
}
